eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8085
zuul:
  routes:
    service-consumer: /service-consumer/**
    service-provider: /service-provider/**
  retryable: true

#网关超时时间
