spring:
  application:
    name: service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
    fetch-registry: true #要不要去注册中心获取其他服务的地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8082
server:
  port: 8082
hystrix:
  metrics:
    enabled: false
